# File used by voici, contains dependencies used in the notebooks
name: voici-env
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - ipycanvas
  - ipywidgets
  - numpy
