name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
              python-version: '3.11'
      - name: Setup mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.6-0' # any version from https://github.com/mamba-org/micromamba-releases
          environment-file: environment.yml
          init-shell: >-
            bash
          cache-environment: true
          post-cleanup: 'all'
      - name: Export notebooks
        run: |
          voici build notebooks --output-dir dist | true
          mkdir dist/files
          voici build notebooks --output-dir dist
        shell: micromamba-shell {0}
        #   run: |
        #     pip install pdm
        #     pdm install
        # - name: Build the JupyterLite site
        #   run: |
        #     pdm run jupyter lite build --contents content --output-dir dist
        # - name: post-treatment
        #   run: |
        #     pdm run python other/post_treatment.py dist/files/
        # - name: Upload artifact
        #   uses: actions/upload-pages-artifact@v3
        #   with:
        #     path: ./dist

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
